languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "ISCI"
copyright = "© Islamic Society of Cayman Islands - All rights reserved"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["announcements", "new-and-events", "services-and-facilities", "islam-in-cayman"]
  description = "Islamic Society of Cayman Islands - Serving the Muslim community in the Cayman Islands"

[params.author]
  name = "Islamic Society of Cayman Islands"
  # image = "img/author.jpg"
  headline = "Serving the Muslim community in the Cayman Islands"
  bio = "Welcome to ISCI! We serve the Muslim community in the Cayman Islands with prayer services, educational programs, and community events. Join us in building a strong, supportive Islamic community."
  links = [
    { email = "mailto:info@isci.ky" },
    { facebook = "https://www.facebook.com/islamic.society.cayman.islands" },
    { instagram = "https://www.instagram.com/islamic.society.cayman.islands" },
    { x-twitter = "https://www.twitter.com/islamic.society.cayman.islands" },
    { youtube = "https://www.youtube.com/islamic.society.cayman.islands" },
  ]
