# -- Main Menu --
# Islamic Society of Cayman Islands Menu Configuration
# Based on the original PaperMod configuration

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  identifier = "about-us"
  name = "About Us"
  weight = 20

[[main]]
  name = "Our Organisation and History"
  url = "/about-us/organisation-and-history/"
  parent = "about-us"
  weight = 30

[[main]]
  name = "About Our Imam"
  url = "/about-us/our-imam/"
  parent = "about-us"
  weight = 40

[[main]]
  identifier = "services-and-facilities"
  name = "Services and Facilities"
  weight = 50

[[main]]
  name = "Masjid Activities"
  url = "/services-and-facilities/masjid-activities/"
  parent = "services-and-facilities"
  weight = 51

[[main]]
  name = "Daily Salaah"
  url = "/services-and-facilities/daily-salaah/"
  parent = "services-and-facilities"
  weight = 52

[[main]]
  name = "Islam Classes for Children"
  url = "/services-and-facilities/islam-classes-for-children/"
  parent = "services-and-facilities"
  weight = 53

[[main]]
  name = "Daily Lectures"
  url = "/services-and-facilities/daily-lectures/"
  parent = "services-and-facilities"
  weight = 54

[[main]]
  name = "Sisters Learning Circle"
  url = "/services-and-facilities/sisters-learning-circle/"
  parent = "services-and-facilities"
  weight = 55

[[main]]
  name = "Masjid Services"
  url = "/services-and-facilities/masjid-services/"
  parent = "services-and-facilities"
  weight = 56

[[main]]
  name = "Ramadhan Programme"
  url = "/services-and-facilities/ramadhan-programme/"
  parent = "services-and-facilities"
  weight = 57

[[main]]
  name = "Announcements"
  url = "/announcements/"
  weight = 60

[[main]]
  name = "News & Events"
  url = "/new-and-events/"
  weight = 70

[[main]]
  name = "Donate"
  url = "/donate/"
  weight = 80

[[main]]
  name = "Islam in Cayman"
  url = "/islam-in-cayman/"
  weight = 90
  
[[main]]
  name = "Contact Us"
  url = "/contact-us/"
  weight = 100

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
