# -- Main Menu --
# Islamic Society of Cayman Islands Menu Configuration
# Based on the original PaperMod configuration

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  identifier = "about-us"
  name = "About Us"
  weight = 20

[[main]]
  name = "Our Organisation and History"
  url = "/about-us/organisation-and-history/"
  parent = "about-us"
  weight = 30

[[main]]
  name = "About Our Imam"
  url = "/about-us/our-imam/"
  parent = "about-us"
  weight = 40

[[main]]
  name = "Services and Facilities"
  url = "/services-and-facilities/"
  weight = 50

[[main]]
  name = "Announcements"
  url = "/announcements/"
  weight = 60

[[main]]
  name = "News & Events"
  url = "/new-and-events/"
  weight = 70

[[main]]
  name = "Donate"
  url = "/donate/"
  weight = 80

[[main]]
  name = "Islam in Cayman"
  url = "/islam-in-cayman/"
  weight = 90
  
[[main]]
  name = "Contact Us"
  url = "/contact-us/"
  weight = 100

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
